from pydantic import BaseModel, Field
from typing import List, Optional, Any
from datetime import datetime

class RiskAssessmentBase(BaseModel):
    shipment_id: int
    risk_score: float = Field(..., ge=0.0, le=10.0, description="Risk score from 0 (safe) to 10 (critical)")
    risk_category: str = Field(..., description="Category: temperature_breach, delay, regulatory, weather")
    reasoning: str = Field(..., description="Detailed explanation generated by AI agent")
    recommended_actions: List[Any] = Field(default=[], description="List of recommended action objects")
    confidence: float = Field(default=0.9, ge=0.0, le=1.0, description="Confidence score between 0 and 1")

class RiskAssessmentCreate(RiskAssessmentBase):
    agent_id: str = Field(default="claude_risk_detector_v1")

class RiskAssessmentRead(RiskAssessmentBase):
    id: int
    agent_id: str
    created_at: datetime

    class Config:
        from_attributes = True
